USE railway;
-- ============================================
-- UPDATE COURSE DESCRIPTIONS
-- ============================================

-- Course 1: Introduction to Psychology
UPDATE courses SET description = 'Discover the fascinating world of human behavior and mental processes in this comprehensive introduction to psychology. This 8-week course explores fundamental psychological concepts, research methods, and major theoretical perspectives that shape our understanding of the mind. Whether you are curious about why people behave the way they do or considering a career in psychology, this course provides a solid foundation. You will learn about brain function and neurotransmitters, how we perceive the world through our senses, principles of learning and conditioning, memory systems, human development from birth to old age, and social influences on behavior. Through engaging content and practical examples, you will gain insights into everyday behavior and develop critical thinking skills. No prerequisites required – just bring your curiosity about human nature. By the end of this journey, you will understand core psychological principles and be able to apply them to real-world situations in your personal and professional life, making you more aware of your own thoughts and better equipped to understand others.' WHERE course_id = 1;

-- Course 2: Cognitive Psychology
UPDATE courses SET description = 'Dive deeper into the inner workings of the human mind with this intermediate-level exploration of cognitive psychology. This 8-week course examines how we think, remember, perceive, and process information in our daily lives. Building on basic psychology knowledge, you will explore cutting-edge research on attention, consciousness, pattern recognition, and memory systems. Learn how your brain represents knowledge, processes language, solves complex problems, and makes decisions. This course is perfect for psychology students, educators, UX designers, or anyone interested in understanding mental processes at a deeper level. You will discover why we sometimes make irrational decisions, how biases affect our thinking, and what strategies can improve memory and problem-solving. Through real-world applications and cognitive experiments, you will gain practical insights into human cognition. Prerequisites include basic psychology knowledge or completion of an introductory psychology course. By the end of this program, you will understand sophisticated cognitive theories and be able to apply them to enhance learning, decision-making, and problem-solving in both personal and professional contexts.' WHERE course_id = 2;

-- Course 3: Business Fundamentals
UPDATE courses SET description = 'Launch your business career or entrepreneurial journey with this comprehensive introduction to business fundamentals. This 8-week course covers essential concepts every business professional needs to know, from strategy and marketing to operations and ethics. Whether you are considering business school, starting your own venture, or simply want to understand how organizations operate, this course provides practical knowledge you can use immediately. You will learn how to analyze markets and competition, understand customer needs, manage operations efficiently, lead and develop teams, read financial statements, make ethical decisions, and develop business plans. Through real-world case studies and interactive examples, you will see how successful companies apply these principles. No prerequisites required – this course welcomes complete beginners and assumes no prior business knowledge. You will gain confidence in business terminology and develop strategic thinking skills. By the end of this 8-week program, you will understand how different business functions work together and be prepared to make informed decisions in any organizational setting or launch your own entrepreneurial venture with a solid foundation.' WHERE course_id = 3;

-- Course 4: Microeconomics
UPDATE courses SET description = 'Understand the economic forces that shape our daily decisions and market outcomes in this engaging introduction to microeconomics. This 8-week course teaches you to think like an economist, analyzing how individuals, households, and firms make choices in a world of scarcity. Perfect for business students, aspiring entrepreneurs, policy enthusiasts, or anyone wanting to understand market dynamics, this course demystifies economic concepts through practical examples. You will learn about opportunity costs and trade-offs, how supply and demand determine prices, price elasticity and consumer behavior, production costs and firm decisions, different market structures from perfect competition to monopoly, and market failures including externalities and public goods. Through interactive examples and real-world applications, you will see economics in action every day. No prerequisites required – just basic math skills and curiosity about how markets work. You will develop analytical thinking and problem-solving abilities that apply far beyond economics. By the end of this course, you will understand market mechanisms, be able to analyze economic policies, and make better-informed decisions as a consumer, worker, or business owner.' WHERE course_id = 4;

-- Course 5: Personal Finance
UPDATE courses SET description = 'Take control of your financial future with this practical, life-changing course on personal finance. This 8-week program teaches you essential money management skills that schools often overlook, from budgeting and saving to investing and retirement planning. Whether you are just starting your career, struggling with debt, or wanting to build wealth, this course provides actionable strategies you can implement immediately. You will learn how to set and achieve SMART financial goals, create and maintain a realistic budget, build emergency funds and choose savings accounts, understand and improve your credit score, invest in stocks, bonds, and mutual funds wisely, plan for a comfortable retirement, protect yourself with appropriate insurance, and optimize your taxes legally. Through hands-on exercises and real-life scenarios, you will develop confidence in financial decision-making. No prerequisites required – this course welcomes everyone regardless of current financial situation or math background. You will gain practical tools and frameworks for financial success. By the end of this 8-week journey, you will have a comprehensive financial plan, understand investment principles, and possess the knowledge to build long-term wealth and financial security for yourself and your family.' WHERE course_id = 5;

-- Course 6: Introduction to Programming
UPDATE courses SET description = 'Begin your coding journey with this beginner-friendly introduction to programming using Python, one of the most popular and versatile programming languages. This 8-week course teaches you fundamental programming concepts that apply across all languages, making it perfect for complete beginners with no prior coding experience. Whether you want to start a tech career, automate tasks, analyze data, or simply understand how software works, this course provides a solid foundation. You will learn about variables, data types, and operators, control flow with if statements and loops, creating reusable functions, working with lists, tuples, and dictionaries, manipulating and formatting text, reading and writing files, handling errors gracefully, and building a complete application as your final project. Through hands-on coding exercises and practical projects, you will write real programs from day one. No prerequisites required – just a computer and willingness to learn. You will develop problem-solving skills and computational thinking. By the end of this 8-week program, you will be able to write functional Python programs, understand code written by others, and have the confidence to continue learning advanced programming concepts and tackle real-world coding challenges.' WHERE course_id = 6;

-- Course 7: Web Development Basics
UPDATE courses SET description = 'Create beautiful, interactive websites from scratch with this comprehensive introduction to web development. This 8-week course teaches you the three core technologies that power every website: HTML for structure, CSS for styling, and JavaScript for interactivity. Perfect for aspiring web developers, entrepreneurs wanting to build their own sites, designers expanding their skills, or anyone curious about how the web works, this course assumes no prior coding experience. You will learn how to structure web pages with HTML, style websites with CSS including colors, fonts, and layouts, create responsive layouts using Flexbox and Grid, add interactivity with JavaScript basics, manipulate web pages dynamically with the DOM, collect and validate user input through forms, fetch data from APIs and servers, and build mobile-friendly responsive designs. Through hands-on projects, you will build real websites you can showcase. No prerequisites required – just creativity and eagerness to learn. You will gain practical skills used by professional developers daily. By the end of this 8-week journey, you will have a portfolio of working websites, understand modern web development workflows, and be ready to build professional-quality sites or continue learning advanced frameworks and technologies.' WHERE course_id = 7;

-- Course 8: Data Analysis Fundamentals
UPDATE courses SET description = 'Transform raw data into actionable insights with this practical introduction to data analysis. This 8-week course teaches you essential skills for working with data in any field, from business and healthcare to marketing and research. Whether you want to become a data analyst, make data-driven decisions in your current role, or simply understand the numbers around you, this course provides hands-on experience with real datasets. You will learn the complete data analysis process from start to finish, how to load and explore datasets effectively, clean and prepare messy data for analysis, calculate and interpret descriptive statistics, create compelling charts and visualizations, identify correlations and patterns in data, build simple predictive models, and present insights that drive decisions. Through practical exercises with real-world data, you will develop analytical thinking and problem-solving skills. Basic computer skills required; no advanced math or programming experience needed. You will use user-friendly tools and learn at your own pace. By the end of this 8-week program, you will be able to confidently analyze datasets, visualize trends, and communicate findings effectively, making you a more valuable professional in any data-driven field and enabling you to make better informed decisions.' WHERE course_id = 8;

-- Course 9: Nutrition and Wellness
UPDATE courses SET description = 'Transform your health and wellbeing with this comprehensive guide to nutrition and healthy living. This 8-week course cuts through diet fads and conflicting information to teach you evidence-based nutrition principles that work. Whether you want to improve your energy, manage your weight, prevent disease, or simply eat better, this course provides practical strategies you can implement immediately in your daily life. You will learn about macronutrients and micronutrients your body needs, how to read and understand food labels accurately, plan balanced, nutritious meals for the week, manage weight through healthy approaches, evaluate vegetarian, vegan, and other dietary patterns, maintain proper hydration throughout the day, handle and store food safely to prevent illness, and make eco-friendly sustainable food choices. Through meal planning exercises and practical tips, you will develop lifelong healthy eating habits. No prerequisites required – this course welcomes everyone regardless of current fitness level or nutrition knowledge. You will gain science-based information without overwhelming jargon. By the end of this 8-week journey, you will understand nutritional principles, be able to make informed food choices, plan healthy meals confidently, and have the tools to maintain a healthy lifestyle that supports your goals and wellbeing for years to come.' WHERE course_id = 9;

-- Course 10: Fitness and Exercise Science
UPDATE courses SET description = 'Build strength, endurance, and lifelong fitness habits with this comprehensive introduction to exercise science and physical training. This 8-week course teaches you the scientific principles behind effective workouts, helping you design safe, efficient exercise programs tailored to your goals. Whether you are a complete beginner, returning to fitness after a break, or wanting to optimize your current routine, this course provides expert guidance without requiring gym membership or expensive equipment. You will learn the key components of physical fitness, how to design effective cardiovascular workouts for heart health, perform strength training exercises to build muscle, improve flexibility and mobility safely through stretching, create personalized workout programs that fit your lifestyle, recognize and prevent common exercise injuries, optimize recovery with rest and nutrition strategies, and develop sustainable fitness habits for life. Through video demonstrations and progressive training plans, you will build confidence in exercising safely. No prerequisites or current fitness level required – start where you are. You will understand exercise science and proper form. By the end of this 8-week program, you will have a personalized fitness plan, understand how to exercise effectively and safely, and possess the knowledge and motivation to maintain an active, healthy lifestyle.' WHERE course_id = 10;

-- Course 11: Digital Design Basics
UPDATE courses SET description = 'Unleash your creativity and learn to create stunning visual designs with this comprehensive introduction to digital design. This 8-week course teaches you fundamental design principles used by professionals across all visual mediums, from logos and branding to social media graphics and websites. Whether you are an aspiring designer, entrepreneur needing to create your own marketing materials, social media manager, or anyone wanting to develop their visual communication skills, this course provides practical knowledge you can apply immediately. You will learn essential design principles including balance and hierarchy, color theory and how to create effective palettes, typography and choosing appropriate typefaces, composition techniques for arranging elements, how to use popular design software and tools, create memorable logos and brand identities, design engaging graphics for social media platforms, and build a professional portfolio showcasing your work. Through hands-on projects and creative exercises, you will develop your unique design style. No prerequisites or artistic background required – just creativity and willingness to learn. You will gain confidence in design decisions. By the end of this 8-week journey, you will understand design fundamentals, be able to create professional-quality graphics, have a portfolio of work to showcase, and possess skills valuable in numerous careers and personal projects.' WHERE course_id = 11;

-- Course 12: Photography Fundamentals
UPDATE courses SET description = 'Capture stunning images and master your camera with this comprehensive introduction to photography. This 8-week course teaches you both the technical and artistic sides of photography, transforming you from someone who simply takes snapshots into a photographer who creates compelling images. Whether you have a DSLR, mirrorless camera, or even a smartphone, and want to take professional-quality photos, this course covers essential techniques that apply to all cameras. You will learn how to understand and control your camera settings, master the exposure triangle of aperture, shutter speed, and ISO, compose compelling photographs using proven rules, use natural and artificial lighting creatively, capture beautiful portraits that reveal personality, shoot stunning landscape and nature photography, edit and enhance your photos in post-processing, and curate a portfolio of your best work. Through practical assignments and photo challenges, you will practice skills weekly and receive feedback. No prerequisites required – any camera works, even smartphones with manual controls. You will develop your photographic eye and technical skills simultaneously. By the end of this 8-week program, you will shoot in manual mode confidently, understand composition and lighting principles, have a portfolio showcasing your best images, and possess skills to pursue photography professionally or as a serious hobby.' WHERE course_id = 12;

-- Course 13: Creative Writing
UPDATE courses SET description = 'Discover your unique voice and craft compelling stories with this inspiring creative writing course. This 8-week program teaches you essential storytelling techniques used by successful authors across all genres, from fiction and memoir to screenwriting and poetry. Whether you dream of publishing a novel, writing for television, or simply want to express yourself more effectively through words, this course provides the tools and encouragement to bring your stories to life. You will learn how to find and develop your authentic writing voice, create memorable, complex characters readers love, structure compelling plots with satisfying arcs, write realistic, engaging dialogue that reveals character, build vivid settings and immersive worlds, use "show, don''t tell" and advanced techniques, edit and revise your drafts effectively, and understand traditional and self-publishing options. Through writing exercises and peer feedback, you will complete several polished pieces. No prerequisites required – just stories to tell and willingness to write regularly. You will join a supportive community of fellow writers. By the end of this 8-week journey, you will have completed several stories or chapters, understand the craft of storytelling, developed a consistent writing practice, and gained confidence in your ability to write compelling narratives that engage readers and express your unique perspective.' WHERE course_id = 13;

-- Course 14: Public Speaking
UPDATE courses SET description = 'Overcome your fear and become a confident, engaging speaker with this transformative public speaking course. This 8-week program teaches you proven techniques used by professional speakers, helping you deliver presentations that inform, inspire, and persuade. Whether you need to present at work, speak at events, pitch ideas to investors, or simply want to communicate more effectively, this course provides practical strategies that work in any speaking situation. You will learn how to manage and overcome public speaking anxiety, structure speeches and presentations effectively, use your voice powerfully with proper techniques, employ body language and nonverbal communication, design and use visual aids like slides effectively, build persuasive arguments that influence audiences, think and speak confidently without preparation, and deliver polished professional presentations. Through practice speeches with constructive feedback, you will build real speaking experience in a supportive environment. No prerequisites required – all confidence levels welcome from terrified beginners to experienced speakers wanting to improve. You will practice in low-pressure settings before high-stakes situations. By the end of this 8-week program, you will have delivered multiple presentations, overcome speaking anxiety significantly, mastered essential presentation skills, and gained the confidence to speak compellingly in any professional or personal situation.' WHERE course_id = 14;

-- Course 15: Leadership Skills
UPDATE courses SET description = 'Develop the essential skills to lead teams and organizations effectively with this comprehensive leadership course. This 8-week intermediate program explores proven leadership theories and practical techniques used by successful leaders across industries. Whether you are a new manager, aspiring leader, team lead, entrepreneur, or professional wanting to enhance your influence, this course provides frameworks and strategies for leading with confidence and integrity. You will learn what makes leaders effective through established theories, assess your personal leadership style and develop self-awareness, communicate effectively through active listening and feedback, build and motivate high-performing teams, make difficult decisions using proven frameworks, resolve conflicts and disagreements constructively, guide organizations and teams through change successfully, and lead with integrity and strong ethical values. Through case studies, leadership assessments, and practical exercises, you will apply concepts to real situations. Prerequisites include work experience or completion of business fundamentals; this intermediate course builds on basic management concepts. You will develop authentic leadership presence. By the end of this 8-week program, you will understand your leadership strengths and areas for growth, possess practical tools for leading effectively, be able to inspire and motivate teams, and have the confidence to take on greater leadership responsibilities in your organization or venture.' WHERE course_id = 15;


